language: node_js
node_js:
  - "10"
sudo: required
env:
  global: 
    - CC_TEST_REPORTER_ID=c7272d27dd52b04d23e320c6377ca02828aff79952ccb59adfdf192a7762eb3a

install:
  - npm install

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
  - npm run coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
